import type { ArchitectureASTModel } from "./ArchitectureAST";

export interface GeneratedArtifacts {
  openApiJson: string;
  djangoViewsPy: string;
  reactComponentTsx: string;
  terraformMainTf: string;
}

export class CodeGeneratorEngine {
  generateCode(model: ArchitectureASTModel): GeneratedArtifacts {
    const provenance = `// Generated By: Atlas Studio v1.0\n// Source Model: ${model.title} (${model.id})\n// Provenance: Deterministic Generator\n\n`;

    const openApiJson = JSON.stringify(
      {
        openapi: "3.0.0",
        info: { title: model.title, version: "1.0.0" },
        paths: {
          "/api/tasks/": {
            get: { summary: "List all tasks", responses: { "200": { description: "Success" } } },
            post: { summary: "Create task", responses: { "201": { description: "Created" } } },
          },
        },
      },
      null,
      2
    );

    const djangoViewsPy = `${provenance}from rest_framework import viewsets, permissions\nfrom .models import Task\nfrom .serializers import TaskSerializer\n\nclass TaskViewSet(viewsets.ModelViewSet):\n    queryset = Task.objects.all()\n    serializer_class = TaskSerializer\n    permission_classes = [permissions.IsAuthenticated]\n`;

    const reactComponentTsx = `${provenance}import React, { useEffect, useState } from "react";\n\nexport function GeneratedTasksList() {\n  const [tasks, setTasks] = useState([]);\n  return (\n    <div className="p-4 bg-slate-900 text-white font-mono">\n      <h2>Tasks list generated from Atlas Studio</h2>\n    </div>\n  );\n}\n`;

    const terraformMainTf = `${provenance}provider "aws" {\n  region = "us-east-1"\n}\n\nresource "aws_ecs_service" "task_service" {\n  name = "django-task-service"\n  desired_count = 2\n}\n`;

    return {
      openApiJson,
      djangoViewsPy,
      reactComponentTsx,
      terraformMainTf,
    };
  }
}
