import type { CanonicalDeploymentPlan } from "./DeploymentPlanModel";

export interface ManifestArtifacts {
  dockerComposeYml: string;
  kubernetesYaml: string;
  helmValuesYaml: string;
  terraformMainTf: string;
}

export class ManifestGeneratorEngine {
  generateManifests(plan: CanonicalDeploymentPlan): ManifestArtifacts {
    const meta = `# Generated By: Atlas Deployment Intelligence v5.5\n# Plan ID: ${plan.id}\n# Target Env: ${plan.targetEnvironment}\n# Timestamp: ${new Date(plan.provenance.timestamp).toISOString()}\n\n`;

    const dockerComposeYml = `${meta}version: '3.8'\nservices:\n` +
      plan.services.map((s) => `  ${s.name.toLowerCase().replace(/[^a-z0-9]/g, "-")}:\n    image: ${s.name.toLowerCase()}:v1.0\n    ports:\n      - "${s.port}:${s.port}"`).join("\n");

    const kubernetesYaml = `${meta}apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: ${plan.targetEnvironment.toLowerCase()}-app\nspec:\n  replicas: ${plan.scaling.minReplicas}\n  selector:\n    matchLabels:\n      app: atlas-service\n`;

    const helmValuesYaml = `${meta}environment: ${plan.targetEnvironment.toLowerCase()}\nreplicaCount: ${plan.scaling.minReplicas}\nscaling:\n  enabled: true\n  maxReplicas: ${plan.scaling.maxReplicas}\n`;

    const terraformMainTf = `${meta}provider "aws" {\n  region = "us-east-1"\n}\nresource "aws_ecs_cluster" "app_cluster" {\n  name = "atlas-${plan.targetEnvironment.toLowerCase()}-cluster"\n}\n`;

    return {
      dockerComposeYml,
      kubernetesYaml,
      helmValuesYaml,
      terraformMainTf,
    };
  }
}
